title: "Minjae's Life & Review Blog"
description: "Everyday thoughts, honest reviews, and side-projects in AI."
url: "https://minjaecho.github.io"
theme: "minimal-mistakes-jekyll"
paginate: 8
minimal_mistakes_skin: "dark"
google_analytics: "G-XXXXXXXXXX"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
author:
  name: "Minjae Cho (조민제)"
  avatar: "/assets/images/avatar-minjae.jpg"
  location: "Incheon, South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SGT-Cho"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/minjaecho"
    - label: "RSS"
      icon: "fas fa-rss"
      url: "/feed.xml"
comments:
  provider: "disqus"
  disqus: "minjae-life-blog"
search: true